<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0"
	xmlns:p="http://maven.apache.org/POM/4.0.0" xmlns="http://maven.apache.org/POM/4.0.0">
	<xsl:output method="xml" indent="yes" />
	
	<xsl:variable name="wonder.version">${wonder.version}</xsl:variable>

	<xsl:template match="@*|node()">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>
  
	<xsl:template match="/p:project">
		<xsl:copy><!-- copy element then copy its attributes -->
			<xsl:copy-of select="@*" />
			<xsl:comment>
				This parent pom was auto generated by splitting pom into parent/child poms
			</xsl:comment>
			<xsl:apply-templates />
		</xsl:copy>
	</xsl:template>
	<xsl:template match="/p:project/p:modelVersion">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="/p:project/p:groupId">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="/p:project/p:artifactId">
		<xsl:copy>
			generic-woparent
		</xsl:copy>
	</xsl:template>
	<xsl:template match="/p:project/p:version">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="/p:project/p:packaging">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="/p:project/p:name">
		<xsl:copy>
			Wonder generic woparent
		</xsl:copy>
		<xsl:element name="description">
			Generic woparent for all Wonder/WebObjects projects. Has repositories needed, dependency
			management, etc. Override in your project pom when necessary items like
			distributionManagement. Sections from the wonder master pom are passed through to create
			the parent pom. Also, a wonder.version parameter is created, its value based off the
			wonder master pom.
		</xsl:element>
	</xsl:template>
	<xsl:template match="/p:project/p:url">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="/p:project/p:inceptionYear">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="/p:project/p:organization">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="/p:project/p:licenses">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="/p:project/p:developers">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="/p:project/p:contributors">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="/p:project/p:mailingLists">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="/p:project/p:prerequisites">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="/p:project/p:scm">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="/p:project/p:distributionManagement">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="/p:project/p:properties">
		<xsl:copy>
			<xsl:element name="wonder.version">
				<xsl:value-of select="/p:project/p:version" />
			</xsl:element>
			<xsl:apply-templates />
		</xsl:copy>
	</xsl:template>
	<xsl:template match="/p:project/p:properties/p:project.build.sourceEncoding">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="/p:project/p:properties/p:project.reporting.outputEncoding">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="/p:project/p:properties/p:webobjects.version">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="/p:project/p:properties/p:skip.apple.frameworks">
		<xsl:copy>
			false
		</xsl:copy>
	</xsl:template>
	<xsl:template match="/p:project/p:dependencyManagement">
		<xsl:copy-of select="." />
	<xsl:apply-templates select="node()" /> 
	<!--expose child node set to fixup project.version -->
	</xsl:template>
	
	<!-- to change project.version -->
	<xsl:template match ="p:dependencies/p:dependency/p:version/text()" >p:$wonder.version
		<xsl:message>aaa<xsl:value-of select="$wonder.version" /></xsl:message>
		<xsl:value-of select="$wonder.version" />
	</xsl:template>
	<xsl:template match="/p:project/p:repositories">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="/p:project/p:pluginRepositories">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="/p:project/p:build">
		<xsl:copy-of select="." />
	</xsl:template>
	<xsl:template match="text()" />
</xsl:stylesheet>